fruits = [
    "apple",
    "banana",
    "orange",
    "grapefruit",
    "pear",
    "kiwi",
    "pineapple",
    "mango",
    "watermelon",
    "strawberry",
    "blueberry",
    "raspberry",
    "cherry",
    "apricot",
    "peach",
    "plum",
    "lemon",
    "lime",
    "coconut",
    "pomegranate",
    "papaya",
    "guava",
    "dragonfruit",
    "avocado",
    "melon",
    "cranberry",
    "blackberry",
    "fig",
    "grape",
    "kiwifruit",
    "passionfruit",
    "mangosteen",
    "persimmon",
    "nectarine",
    "quince",
    "starfruit",
    "tangerine",
    "apricot",
    "banana",
    "apple",
    "apricot",
    "banana",
    "avocado",
    "berry",
    "blackberry",
    "blueberry",
    "cantaloupe",
    "cherry",
    "citron",
    "citrus",
    "coconut",
    "cranberry",
    "cucumber",
    "currant",
    "date",
    "dragonfruit",
    "durian",
    "elderberry",
    "fig",
    "grape",
    "grapefruit",
    "guava",
    "honeydew",
    "jackfruit",
    "kiwi",
    "kumquat",
    "lemon",
    "lime",
    "lychee",
    "mango",
    "melon",
    "mulberry",
    "nectarine",
    "orange",
    "papaya",
    "passionfruit",
    "peach",
    "pear",
    "persimmon",
    "pineapple",
    "plum",
    "pomegranate",
    "prune",
    "pumpkin",
    "raspberry",
    "starfruit",
    "strawberry",
    "tamarind",
    "tangerine",
    "watermelon",
    "yuzu",
]

animals = [
    "Dog",
    "Cat",
    "Elephant",
    "Lion",
    "Tiger",
    "Bear",
    "Giraffe",
    "Zebra",
    "Monkey",
    "Horse",
    "Cow",
    "Pig",
    "Sheep",
    "Goat",
    "Rabbit",
    "Kangaroo",
    "Hippopotamus",
    "Rhinoceros",
    "Deer",
    "Fox",
    "Wolf",
    "Dolphin",
    "Whale",
    "Shark",
    "Penguin",
    "Eagle",
    "Hawk",
    "Parrot",
    "Owl",
    "Crocodile",
    "Alligator",
    "Turtle",
    "Snail",
    "Frog",
    "Toad",
    "Lizard",
    "Snake",
    "Spider",
    "Bee",
    "Butterfly",
    "Ladybug",
    "Ant",
    "Grasshopper",
    "Dragonfly",
    "Centipede",
    "Millipede",
    "Jellyfish",
    "Starfish",
    "Octopus",
    "Crab",
    "Lobster",
    "Fish",
    "Shark",
    "Dolphin",
    "Octopus",
    "Starfish",
    "Whale",
    "Seahorse",
    "Jellyfish",
    "Lobster",
    "Crab",
    "Penguin",
    "Polar Bear",
    "Panda",
    "Koala",
    "Kangaroo",
    "Gorilla",
    "Chimpanzee",
    "Orangutan",
    "Elephant",
    "Rhinoceros",
    "Giraffe",
    "Zebra",
    "Lion",
    "Tiger",
    "Leopard",
    "Cheetah",
    "Hyena",
    "Wolf",
    "Fox",
    "Bear",
    "Deer",
    "Moose",
    "Elk",
    "Giraffe",
    "Camel",
    "Elephant",
    "Rhinoceros",
    "Hippopotamus",
    "Buffalo",
    "Zebra",
    "Kangaroo",
    "Koala",
    "Platypus",
    "Tasmanian Devil",
    "Crocodile",
    "Alligator",
    "Komodo Dragon",
    "Snake",
    "Turtle",
]

numbers = [
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "thirteen",
    "fourteen",
    "fifteen",
    "sixteen",
    "seventeen",
    "eighteen",
    "nineteen",
    "twenty",
    "twenty one",
    "twenty two",
    "twenty three",
    "twenty four",
    "twenty five",
    "twenty six",
    "twenty seven",
    "twenty eight",
    "twenty nine",
    "thirty",
    "thirty one",
    "thirty two",
    "thirty three",
    "thirty four",
    "thirty five",
    "thirty six",
    "thirty seven",
    "thirty eight",
    "thirty nine",
    "forty",
    "forty one",
    "forty two",
    "forty three",
    "forty four",
    "forty five",
    "forty six",
    "forty seven",
    "forty eight",
    "forty nine",
    "fifty",
    "fifty one",
    "fifty two",
    "fifty three",
    "fifty four",
    "fifty five",
    "fifty six",
    "fifty seven",
    "fifty eight",
    "fifty nine",
    "sixty",
    "sixty one",
    "sixty two",
    "sixty three",
    "sixty four",
    "sixty five",
    "sixty six",
    "sixty seven",
    "sixty eight",
    "sixty nine",
    "seventy",
    "seventy one",
    "seventy two",
    "seventy three",
    "seventy four",
    "seventy five",
    "seventy six",
    "seventy seven",
    "seventy eight",
    "seventy nine",
    "eighty",
    "eighty one",
    "eighty two",
    "eighty three",
    "eighty four",
    "eighty five",
    "eighty six",
    "eighty seven",
    "eighty eight",
    "eighty nine",
    "ninety",
    "ninety one",
    "ninety two",
    "ninety three",
    "ninety four",
    "ninety five",
    "ninety six",
    "ninety seven",
    "ninety eight",
    "ninety nine",
    "one hundred",
]

countries = [
    "Lithuania",
    "Latvia",
    "Estonia",
    "United States",
    "Canada",
    "Mexico",
    "United Kingdom",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Portugal",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Netherlands",
    "Belgium",
    "Switzerland",
    "Austria",
    "Poland",
    "Czech Republic",
    "Slovakia",
    "Hungary",
    "Slovenia",
    "Croatia",
    "Serbia",
    "Bulgaria",
    "Romania",
    "Greece",
    "Turkey",
    "Russia",
    "Ukraine",
    "Belarus",
    "Kazakhstan",
    "China",
    "Japan",
    "South Korea",
    "India",
    "Australia",
    "New Zealand",
    "Brazil",
    "Argentina",
    "Chile",
    "Peru",
    "Colombia",
    "Venezuela",
    "Egypt",
    "South Africa",
    "Nigeria",
    "Kenya",
    "Morocco",
    "Algeria",
    "Saudi Arabia",
    "United Arab Emirates",
    "Israel",
    "Qatar",
    "Pakistan",
    "Bangladesh",
    "Indonesia",
    "Malaysia",
    "Philippines",
    "Thailand",
    "Vietnam",
    "Singapore",
    "Cambodia",
    "Mongolia",
    "Nepal",
    "Bhutan",
    "Myanmar",
    "Laos",
    "Brunei",
    "Fiji",
    "Tonga",
    "Samoa",
    "Solomon Islands",
    "Kiribati",
    "Tuvalu",
    "Vanuatu",
    "Palau",
    "Marshall Islands",
    "Micronesia",
    "Nauru",
    "Papua New Guinea",
    "Timor-Leste",
    "Antigua and Barbuda",
    "Barbados",
    "Bahamas",
    "Jamaica",
    "Trinidad and Tobago",
    "Grenada",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Dominica",
    "Saint Kitts and Nevis",
    "Belize",
    "Costa Rica",
    "Panama",
    "Nicaragua",
    "Honduras",
    "El Salvador",
    "Guatemala",
]
